version: '2'
services:
  redisdb:
    image: redis
  server:
    build: ./Shortify-server
    ports:
    - "4567:4567"
    depends_on:
     - redisdb
  client:
    build: ./Shortify-client
    ports:
     - "8085:80"